# Rust as the base image
FROM rust:1.49 as build

# Create a new empty shell project
RUN USER=root cargo new --bin balance_management
WORKDIR /balance_management

# Copy our manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# Build only the dependencies to cache them
RUN cargo build --release
RUN rm src/*.rs

# Copy the source code
COPY ./src ./src

# Build for release.
RUN rm ./target/release/deps/balance_management*
RUN cargo build --release

# The final base image
FROM debian:buster-slim

# Copy from the previous build
COPY --from=build /balance_management/target/release/balance_management /usr/src/balance_management

# Run the binary
CMD ["/usr/src/balance_management"]